name: Build and Deploy Backend (NestJS) to Render

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'backend/**'  # Trigger only if there are changes in the backend folder
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the appropriate Node.js version

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Build NestJS app
        run: |
          cd backend
          npm run build

      - name: Deploy to Render
        run: |
          cd backend
          git remote add render https://github.com/YassineAzedine/online-course-platform.git
          git push render main
        env:
          RENDER_API_KEY: ${{ secrets.rnd_as1X1PwNjIUtKdfShtPhnaNWWOhW }}  # Set Render API key in GitHub secrets
